### PR TITLE
fix: follow proto3 specification for default values

### LINKED ISSUE #7: `null` return values do not follow proto3 spec
`string` and `bytes` proto3 types do not have correct default value semantics.

According to the [Protobuf Documentation](https://developers.google.com/protocol-buffers/docs/proto3#default), `string` and `bytes` types should be default initialized to an empty string and empty byte array, respectively.

For reference, my proto type:

``` proto3
message event_arguments {
   string name = 1;
   bytes data = 2;
   repeated bytes impacted = 3;
}
```

Generates a class with the following fields and constructor:

``` ts
  name: string | null;
  data: Uint8Array | null;
  impacted: Array<Uint8Array>;

  constructor(
    name: string | null = null,
    data: Uint8Array | null = null,
    impacted: Array<Uint8Array> = []
  ) {
    this.name = name;
    this.data = data;
    this.impacted = impacted;
  }
  ```
  
I believe removing the `| null` from `Uint8Array` and `string` generated fields would fix the problem.
Note: `impacted` appears to be correct and `| null` should probably remain on all fields marked `optional`.

### PR DESCRIPTION
**Pull request by piotr-oles**
According to the [Protobuf Documentation](https://developers.google.com/protocol-buffers/docs/proto3#default), string and bytes types should be default initialized to an empty string and empty byte array, respectively.

Closes #7

### CODE REVIEW

File: packages/as-proto-gen/src/generate/field.ts [hunk 1]
```diff
@@ -309,31 +311,26 @@ export function generateFieldTypeInstruction(
   }
 }
 
+export function isNullableFieldType(
+  fieldDescriptor: FieldDescriptorProto
+): boolean {
+  const fieldType = fieldDescriptor.getType();
+  assert.ok(fieldType !== undefined);
+
+  return fieldType === Type.TYPE_MESSAGE;
```
Comment (rellfy) [inline packages/as-proto-gen/src/generate/field.ts:320]: Shouldn't this always be false, given that there is no null in protobuf3? It is not possible to distinguish from a default message vs a "null" one AFAIK.
